### ISSUE TITLE
Segments not draggable on touch-screen laptops

### ISSUE THREAD

**Issue by ghost** [jamesalvarez/draggable-piechart#4]
Hi James,

First, thanks for this amazing component!

I've been integrating it into a project, but I seem to be having some difficulty dragging the segments on some device types. The issue seems to be related to touch-screen laptops on Windows 10 (it effects Edge and Chrome, possibly other browsers).

For reference, I tested on the following devices an experienced the issue:

- Lenovo YOGA 80Y7
- Lenovo YOGA 720

I'm wondering if the problem lies in the computer possessing multiple input types (mouse / trackpad and touch screen). Could it be a source of confusion for the pie chart, in that it is expecting input from the touch screen instead of the mouse or vice versa? 

Or maybe the input source that you use within javascript is different when multiple options are available e.g. instead of a single source, it's an array and you have to select an item within it?

Thanks in advance for your help, and if you need me to provide further details or test things out for you, please do let me know.

P.S. I'm using the latest version of the component.

Thanks!
Matt

**Comment by jamesalvarez** [comment]
Hi Matt

Due to my current workload, I cannot spend time helping you on this!  touch
and mouse events were a mess at the time i made this, and I know things
have been updated recently...
https://developer.mozilla.org/en-US/docs/Web/API/Touch_events/Supporting_both_TouchEvent_and_MouseEvent

James

James

**Comment by ghost** [comment]
Thanks James. I’ll take a look and see if I can figure something out.
