### ISSUE TITLE
Table shows only in no-colour mode

### ISSUE THREAD

**Issue by waterbear83** [jamesalvarez/draggable-piechart#5]
Hello James,

Would be very helpful to have a short reference in your readme file of how to show the table with percentages also when you use the colored version of the chart.

https://codepen.io/Waterbear83/pen/yLNqVBZ?editors=0010

Your work is very nice, thanks a lot!

**Comment by jamesalvarez** [comment]
Glad its useful! - For the readme though, I like to keep it brief and I think it should be possible to cut and paste various things from the examples there already to do this - might have a look to adding more examples when I come round to updating the project later this year.
