### ISSUE TITLE
Pie chart ignores mouse input when touch input is available

### ISSUE THREAD

**Issue by NatSquared** [jamesalvarez/draggable-piechart#9]
Whenever window.ontouchdown exists or navigator.maxTouchPoints >= 1, all mouse input is ignored. This is a huge problem on devices where mouse input is the primary input. This problem could be solved by binding both touch events and mouse events whenever a mouse and touchscreen are present.

**Comment by jamesalvarez** [comment]
Thanks for the issue, good point.  Would you be prepared to test the touchmouse branch I have committed a change to?  It works on my touch device and mouse device, but I have no touch device with a mouse.

**Comment by NatSquared** [comment]
Oh, sure; I'd be happy to! Send me a demo or something and I'll see how it works :)

**Comment by NatSquared** [comment]
Okay; nevermind, I found your `touchmouse` branch and tested it locally. It works beautifully! I think this issue is closed as soon as the branch gets merged.

**Comment by jamesalvarez** [comment]
Ok all fixed then.  Thanks for doing that!
